### ISSUE TITLE
Support OpenSearch

### ISSUE THREAD

**Issue by mharleydev** [greentfrapp/redditle#8]
I'd like to add Redditle as a search engine to Firefox. It seems the only way that's possible is if a search engine supports OpenSearch. I don't think there's a documented way to manually add a search engine to Firefox.

[Firefox documentation](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox)

**Comment by greentfrapp** [comment]
Thanks @mharleydev for the suggestion, I've just added support for OpenSearch - you should be able to add it as a search engine now!
